export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const PRODUCT_ADD = "PRODUCT_ADD";
export const PRODUCTS_LIST = "PRODUCTS_LIST";
export const PRODUCT_REMOVE = "PRODUCT_REMOVE";
export const PRODUCT_UPDATE = "PRODUCT_UPDATE";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const HIDE_MESSAGE = "HIDE_MESSAGE";

export const COULD_REMOVE_CATEGORY = "COULD_REMOVE_CATEGORY";
export const CURRENT_CATEGORY = "CURRENT_CATEGORY";

export const ADD_TO_CART = "ADD_TO_CART";
export const GET_CART_PRODUCTS = "GET_CART_PRODUCTS";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
