export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const PRODUCT_ADD = "PRODUCT_ADD";
export const PRODUCTS_LIST = "PRODUCTS_LIST";
export const PRODUCT_REMOVE = "PRODUCT_REMOVE";
